---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-mysql-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: default
  source:
    repoURL: https://percona.github.io/percona-helm-charts
    targetRevision: main
    path: apps/percona/pxc
  destination:
    server: https://kubernetes.default.svc
    namespace: percona-mysql-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true # <-- Auto-create namespace if needed

