---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-mysql-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: default
  source:
    repoURL: https://percona.github.io/percona-helm-charts
    chart: pxc-operator
    targetRevision: 1.14.0 # Use the latest or desired version
    helm:
      releaseName: pxc-operator
      values: |
        watchAllNamespaces: true
        namespace: percona
  destination:
    server: https://kubernetes.default.svc
    namespace: percona
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
